CREATE SCHEMA IF NOT EXISTS EMPRESA;
USE EMPRESA;

CREATE TABLE IF NOT EXISTS USER(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SUPERVISOR_EMAIL VARCHAR(100)
    /*,
    CREATION_DATE TIMESTAMP,
    CREATION_USER VARCHAR(30),
    MODIFICATION_DATE TIMESTAMP,
    MODIFICATION_USER VARCHAR(30),
    DEACTIVATION_DATE TIMESTAMP,
    DEACTIVATION_USER VARCHAR(30)
    */
);
ALTER TABLE USER MODIFY COLUMN PASSWORD VARCHAR(200) NOT NULL;

CREATE TABLE IF NOT EXISTS ROLE(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(30) NOT NULL
    /*,
    CREATION_DATE TIMESTAMP,
    CREATION_USER VARCHAR(30),
    MODIFICATION_DATE TIMESTAMP,
    MODIFICATION_USER VARCHAR(30),
    DEACTIVATION_DATE TIMESTAMP,
    DEACTIVATION_USER VARCHAR(30)
    */
);

CREATE TABLE IF NOT EXISTS USER_ROLE(
	USER_ID BIGINT,
    ROLE_ID BIGINT,
    PRIMARY KEY(USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
    /*,
    CREATION_DATE TIMESTAMP,
    CREATION_USER VARCHAR(30),
    MODIFICATION_DATE TIMESTAMP,
    MODIFICATION_USER VARCHAR(30),
    DEACTIVATION_DATE TIMESTAMP,
    DEACTIVATION_USER VARCHAR(30)
    */
);

INSERT INTO USER(USERNAME, PASSWORD, EMAIL, SUPERVISOR_EMAIL) VALUES ('admin', '$2a$10$WLC4KcRlGln.WjOhUSnEheUxNYEN.MHrXAd0U9y4NS1vlkadUh6wG', 'admin@gmail.com', null);
INSERT INTO ROLE(NAME) VALUES('admin'),('reader');
INSERT INTO USER_ROLE(USER_ID, ROLE_ID) VALUES(1,1);

select * from USER;
select * from ROLE;
select * from USER_ROLE;

show tables;

-- DROP TABLE USER_ROLE;
-- DROP TABLE ROLE;
-- DROP TABLE USUARIO;
